manifest:
  remotes:
    - name: amkarkhi
      url-base: https://github.com/amkarkhi
  projects:
    - name: zmk
      remote: amkarkhi
      revision: main
      import: app/west.yml
  self:
    path: config
